/**
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@kinde.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package au.kinde.sdk.api.model

import au.kinde.sdk.api.model.CreateUserRequestIdentitiesInner
import au.kinde.sdk.api.model.CreateUserRequestProfile

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param profile 
 * @param identities 
 */

data class CreateUserRequest (

    @SerializedName("profile")
    val profile: CreateUserRequestProfile? = null,

    @SerializedName("identities")
    val identities: kotlin.collections.List<CreateUserRequestIdentitiesInner>? = null

)

