/**
 * Kinde Management API
 *
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@kinde.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package au.kinde.sdk.api.model

import au.kinde.sdk.api.model.UserIdentityResult

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param type 
 * @param result 
 */

data class UserIdentity (

    @SerializedName("type")
    val type: kotlin.String? = null,

    @SerializedName("result")
    val result: UserIdentityResult? = null

)

